################################## NETWORK #####################################

# Listen on all interfaces (inside the container)
bind 127.0.0.1

# Default Redis port
port 6379

# Protected mode off since we’re binding 0.0.0.0 in a controlled dev environment
protected-mode no


############################### PERSISTENCE ####################################

# Enable append-only file so Celery can recover state after a restart
appendonly yes
appendfilename "appendonly.aof"

# RDB snapshots every 60 seconds if at least 1 change happened
save 60 1


############################### SECURITY #######################################

# In dev you can leave this off, but for any shared network uncomment:
# requirepass yourStrongPassword