"""Export an E2E fixture module from a real disc record in the DB.

Usage:
    python Backend/scripts/export_e2e_fixture.py \
        --disc-id <uuid> \
        --fixture-name hit_movie \
        --expected-workflow hit \
        [--discdb-disabled] \
        [--out Backend/tests/fixtures/e2e_fixtures/hit_movie.py]

Reads the disc's stored discinfo (info_log + per-title metadata), constructs a
``Fixture`` payload, and writes a self-contained Python module that the E2E
bootstrap can load via ``E2E_FIXTURE=<fixture_name>``.

Intended as a one-shot per-disc tool. Run it against a disc you've already
ripped through mkv-auto's normal flow; the resulting fixture preserves the
disc's content_hash so live TheDiscDB lookups against the fixture behave
exactly as they did during the original rip.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Backend on path for api/models access
_backend = Path(__file__).resolve().parent.parent
if str(_backend) not in sys.path:
    sys.path.insert(0, str(_backend))


def _python_repr(value) -> str:
    """Pretty-print as Python literal — pprint.pformat so None/True/False/etc.
    render as Python (not JSON null/true/false)."""
    import pprint
    return pprint.pformat(value, width=120, sort_dicts=False)


def _build_payload_from_disc(disc, titles) -> dict:
    """Construct a MockDrive discinfo_payload from a stored Disc row + titles."""
    di = disc.disc_info or {}
    payload = {
        "disc_num": "1",
        "mount_point": "/dev/sr0",
        "disc_hash": disc.content_hash,
        "content_hash": disc.content_hash,
        "info_title": disc.info_title or disc.disc_name or "Unknown",
        "format": disc.format or "Blu-Ray",
        "disc_format": disc.format or "Blu-Ray",
        "show_title": disc.info_title or disc.disc_name,
        "show_image": None,
        "resolution": di.get("resolution") or "1080p",
        "title_type": "movie",
        "tracks": {},
        "titles": {},
        "info_log": di.get("info_log") or di.get("raw_info_log") or "",
        "raw_info_log": di.get("raw_info_log") or di.get("info_log") or "",
    }
    # Build the tracks/titles maps from disc_titles.
    for t in titles:
        sf = t.source_file
        if not sf:
            continue
        payload["tracks"][sf] = {
            "season": str(getattr(t, "season", None) or "1"),
            "episode": str(getattr(t, "episode", None) or "1"),
            "episode_name": t.title or "",
            "format": (t.type or "MainFeature") if (t.type or "").lower() == "mainmovie" else (t.type or "Extra"),
        }
        payload["titles"][sf] = {
            "file": sf,
            "title": t.title or "",
            "description": t.comment or "",
        }
    return payload


def _build_mockmkv_titles(titles) -> list[dict]:
    """Construct a MockMKV titles list from disc_titles rows."""
    out = []
    for t in titles:
        sf = t.source_file
        if not sf or not sf.endswith(".mpls"):
            continue
        out.append({"file": sf, "size_mb": max(1, int((t.size or 1_000_000) / 1_000_000))})
    return out


def _emit_module(name: str, payload: dict, mockmkv_titles: list[dict],
                 discdb_disabled: bool, expected_workflow: str,
                 source_disc_id: str, source_content_hash: str) -> str:
    """Render the generated fixture .py module text."""
    payload_repr = _python_repr(payload)
    mock_repr = _python_repr(mockmkv_titles)
    return f'''"""{name} fixture — generated from disc_id={source_disc_id} (content_hash={source_content_hash}).

Generated by Backend/scripts/export_e2e_fixture.py. Regenerate by re-running
the script against the same disc record.

Faithful to the real disc as it was scanned through mkv-auto's normal flow:
content_hash is preserved so live TheDiscDB lookups produce the same result
they did during the original rip.
"""
from __future__ import annotations

from ._base import Fixture


_DISCINFO_PAYLOAD = {payload_repr}


_MOCKMKV_TITLES = {mock_repr}


FIXTURE = Fixture(
    name="{name}",
    discinfo_payload=_DISCINFO_PAYLOAD,
    mockmkv_titles=_MOCKMKV_TITLES,
    discdb_disabled={discdb_disabled!r},
    expected_workflow="{expected_workflow}",
    notes="Generated from {source_disc_id} (hash {source_content_hash}).",
)
'''


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Export an E2E fixture from a DB disc record.")
    ap.add_argument("--disc-id", required=True, help="discs.id (UUID) to export")
    ap.add_argument("--fixture-name", required=True, help="fixture module name (e.g. 'hit_movie')")
    ap.add_argument("--expected-workflow", choices=["hit", "miss"], required=True)
    ap.add_argument("--discdb-disabled", action="store_true", help="set settings.discdb_disabled=True for this fixture")
    ap.add_argument("--discdb-url-override", default=None, help="override DISKDBURL (rarely used)")
    ap.add_argument("--out", default=None, help="output path (default: Backend/tests/fixtures/e2e_fixtures/<name>.py)")
    args = ap.parse_args(argv)

    out_path = Path(args.out) if args.out else (
        _backend / "tests" / "fixtures" / "e2e_fixtures" / f"{args.fixture_name}.py"
    )

    from api import database, models

    session = database.SessionLocal()
    try:
        disc = session.query(models.Disc).filter(models.Disc.id == args.disc_id).first()
        if not disc:
            print(f"ERROR: disc {args.disc_id} not found in DB", file=sys.stderr)
            return 2
        titles = (
            session.query(models.DiscTitle)
            .filter(models.DiscTitle.disc_id == args.disc_id)
            .order_by(models.DiscTitle.duration.desc().nullslast())
            .all()
        )
        payload = _build_payload_from_disc(disc, titles)
        mockmkv_titles = _build_mockmkv_titles(titles)

        # Apply CLI overrides
        text = _emit_module(
            name=args.fixture_name,
            payload=payload,
            mockmkv_titles=mockmkv_titles,
            discdb_disabled=args.discdb_disabled,
            expected_workflow=args.expected_workflow,
            source_disc_id=str(disc.id),
            source_content_hash=str(disc.content_hash),
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        print(f"wrote {out_path} (info_log size: {len(payload['info_log'])} bytes, {len(mockmkv_titles)} mockmkv titles)")
        return 0
    finally:
        session.close()


if __name__ == "__main__":
    sys.exit(main())
