"""initial schema

Revision ID: ecde1059ae60
Revises: 
Create Date: 2025-05-26 16:25:56.814841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecde1059ae60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'jobs',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column('disc_num', sa.String(), nullable=False),
        sa.Column('mount_point', sa.String(), nullable=False),
        sa.Column('mode', sa.String(), nullable=False, server_default='copy'),
        sa.Column('status', sa.String(), nullable=False, server_default='pending'),
        sa.Column('progress', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('logs', sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column('result_location', sa.Text(), nullable=True),
        sa.Column(
            'disc_payload',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'")
        ),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text('now()')
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
            onupdate=sa.text('now()')
        ),
    )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
